// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VAddCounter8bit.cpp"
#include "VAddCounter8bit___024root.cpp"
#include "VAddCounter8bit__Trace.cpp"
#include "VAddCounter8bit___024root__Slow.cpp"
#include "VAddCounter8bit__Syms.cpp"
#include "VAddCounter8bit__Trace__Slow.cpp"
