// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VALU8Functions_4bit.cpp"
#include "VALU8Functions_4bit___024root__DepSet_h1290effe__0.cpp"
#include "VALU8Functions_4bit___024root__DepSet_h49894a14__0.cpp"
#include "VALU8Functions_4bit__Trace__0.cpp"
#include "VALU8Functions_4bit__ConstPool_0.cpp"
#include "VALU8Functions_4bit___024root__Slow.cpp"
#include "VALU8Functions_4bit___024root__DepSet_h1290effe__0__Slow.cpp"
#include "VALU8Functions_4bit___024root__DepSet_h49894a14__0__Slow.cpp"
#include "VALU8Functions_4bit__Syms.cpp"
#include "VALU8Functions_4bit__Trace__0__Slow.cpp"
