// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VCyclicRightShiftRegister_PosEdge_8Bit.cpp"
#include "VCyclicRightShiftRegister_PosEdge_8Bit___024root.cpp"
#include "VCyclicRightShiftRegister_PosEdge_8Bit__Trace.cpp"
#include "VCyclicRightShiftRegister_PosEdge_8Bit___024root__Slow.cpp"
#include "VCyclicRightShiftRegister_PosEdge_8Bit__Syms.cpp"
#include "VCyclicRightShiftRegister_PosEdge_8Bit__Trace__Slow.cpp"
