// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VMultiFunctionShiftRegister_NegEdge_4Bit.cpp"
#include "VMultiFunctionShiftRegister_NegEdge_4Bit___024root.cpp"
#include "VMultiFunctionShiftRegister_NegEdge_4Bit__Trace.cpp"
#include "VMultiFunctionShiftRegister_NegEdge_4Bit__ConstPool_0.cpp"
#include "VMultiFunctionShiftRegister_NegEdge_4Bit___024root__Slow.cpp"
#include "VMultiFunctionShiftRegister_NegEdge_4Bit__Syms.cpp"
#include "VMultiFunctionShiftRegister_NegEdge_4Bit__Trace__Slow.cpp"
