// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VMultiShifter_4Bit.cpp"
#include "VMultiShifter_4Bit___024root.cpp"
#include "VMultiShifter_4Bit__Trace.cpp"
#include "VMultiShifter_4Bit__ConstPool_0.cpp"
#include "VMultiShifter_4Bit___024root__Slow.cpp"
#include "VMultiShifter_4Bit__Syms.cpp"
#include "VMultiShifter_4Bit__Trace__Slow.cpp"
