// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VAddCounter2bit.cpp"
#include "VAddCounter2bit___024root.cpp"
#include "VAddCounter2bit__Trace.cpp"
#include "VAddCounter2bit___024root__Slow.cpp"
#include "VAddCounter2bit__Syms.cpp"
#include "VAddCounter2bit__Trace__Slow.cpp"
