// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "VALU8Functions_16bit.cpp"
#include "VALU8Functions_16bit___024root__DepSet_hcc7e5745__0.cpp"
#include "VALU8Functions_16bit___024root__DepSet_h10c11a19__0.cpp"
#include "VALU8Functions_16bit__Trace__0.cpp"
#include "VALU8Functions_16bit___024root__Slow.cpp"
#include "VALU8Functions_16bit___024root__DepSet_hcc7e5745__0__Slow.cpp"
#include "VALU8Functions_16bit___024root__DepSet_h10c11a19__0__Slow.cpp"
#include "VALU8Functions_16bit__Syms.cpp"
#include "VALU8Functions_16bit__Trace__0__Slow.cpp"
